
{{- $fullName := include "gitlabContext.fullname" . }}
{{- $name := include "gitlabContext.name" . }}
{{- $chart := include "gitlabContext.chart" . }}
{{- $releasename := .Release.Name }}
{{- $releaseservice := .Release.Service }}
{{- $annotations := .Values.gitlabContext.ingressExternalPrivate.annotations }}
{{- $ingressClassName := .Values.gitlabContext.ingressExternalPrivate.ingressClassName }}

{{- range $k, $v := .Values.gitlabContext.ingressExternalPrivate.ingresses }}
{{- if $v.enabled }}
---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: gitlab-{{ $k }}-external-private
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ $releasename }}
    heritage: {{ $releaseservice }}
{{- with (merge ($v.annotations | default dict) ($annotations)) }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if and $ingressClassName (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
{{- if $v.tls }}
  tls:
  {{- range $v.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $v.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ default "Prefix" .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
              {{- else }}
              serviceName: {{ .service.service }}
              servicePort: {{ .service.port }}
              {{- end }}
          {{- end }}
  {{- end }}
{{- end }}

{{- end }}
