---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-gitlab-shell
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlabContext.standardLabelsTCPIngress" . | nindent 4 }}
spec:
  entryPoints:
    - gitlab-shell
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ $.Release.Name }}-gitlab-shell
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.gitlab.global.shell.port | default "22" | int }}
